server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  application:
    name: newsGateway
  cloud:
    config:
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: true
  datasource:
    # druid, c3p0, hikari, tomcat
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      username: root
      password: pyb***20000112
      jdbc-url: jdbc:mysql://localhost:3306/sojacnn?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    password: pyb***20000112
#    port: 6379
#    jedis:
#      pool:
#        max-active: 60
#        max-wait: 60
#        max-idle: 10
#  profiles: dev
  jackson:
    date-format: yyyy-MM-dd HH:MM:ss
    time-zone: GMT+8
  cache:
    ehcache:
      config: classpath:ehcache/ehcache.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: Sojacnn_Gateway_01
    prefer-ip-address: true
zuul:
  ignored-services: '*'
  sensitive-headers:
  add-proxy-headers: false
  add-host-header: true
  prefix: /api
  routes:
    newsFeatureConsumer:
      path: /newsFeature/**
      service-id: newsFeatureConsumer
    backgroundSystemConsumer:
      path: /background/**
      service-id: backgroundSystemConsumer
  ignored-patterns: /login, /logout

info:
  app.name: Sojacnn_路由网关_01
  company.name: https://github.com/pyb1430501241
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

logging:
  config: classpath:log4j2/log4j2.xml

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl