server:
  # 端口可以改成自己想要的
  port: 8001
  servlet:
    context-path: /
  max-http-header-size: 128KB

spring:
  application:
    # 同一微服务里所有的同类提供者必须同名, 所对应的微服务名称为此值全大写
    name: newsFeature
  datasource:
    # druid, c3p0, hikari, tomcat
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      username: root
      password: pyb***20000112
      jdbc-url: jdbc:mysql://localhost:3306/sojacnn?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      # 将自己注册到哪一个 Eureka 管理里, 如 Eureka 集群, 则需要注册到所有 Eureka 集群里
      defaultZone: http://localhost:7001/eureka/
  instance:
    # 自己在 Eureka 里的名称, 不可重复
    instance-id: Sojacnn_NewsFeature_生产者_01
    # 显示自己的 IP
    prefer-ip-address: true


info:
  app.name: Sojacnn_NewsFeature_01
  company.name: https://github.com/pyb1430501241
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

logging:
  config: classpath:log4j2/log4j2.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
